[package]
name = "gruph"
version = "0.1.0"
authors = ["rbtsbg"]
edition = "2018"

[lib]
name = "gruph"
path = "src/lib.rs"

[[bin]]
name = "gruph-bin"
path = "src/bin.rs"

[dependencies]
petgraph = "0.5.1"
